src/ProIdeas.UI/Controllers/IdeaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProIdeas.Services.Contracts;
using ProIdeas.UI.Models.IdeaViewModels;
using System.Threading.Tasks;
using System.Linq;

namespace ProIdeas.UI.Controllers
{
    [Authorize]
    [Route("ideas")]
    public class IdeaController : Controller
    {
        private readonly IIdeaService _ideaService;
        public IdeaController(IIdeaService ideaService)
        {
            _ideaService = ideaService;
        }

        // GET: Idea/Details/5
        [HttpGet, Route("{id}/details")]
        public async Task<IActionResult> Details(string id)
        {
            var idea = await _ideaService.GetIdeaAsync(id);

            var model = IdeaInfoViewModel.MapFrom(idea);
            if (model.Pages.Any())
            {
                model.Pages.First().IsActive = true;
            }

            return View(model);
        }

        [HttpGet, Route("create")]
        // GET: Idea/Create
        public IActionResult Create()
        {
            return View(IdeaInfoViewModel.CreateEmpty());
        }

        [HttpGet, Route("{id}/edit")]
        // GET: Idea/Edit
        public async Task<IActionResult> Edit(string id)
        {
            var idea = await _ideaService.GetIdeaAsync(id);

            return View(IdeaInfoViewModel.MapFrom(idea));
        }


        [HttpGet, Route("{id}/images")]
        // GET: Idea/Images
        public async Task<IActionResult> Images(string id)
        {
            var idea = await _ideaService.GetIdeaAsync(id);

            return View(IdeaInfoViewModel.MapFrom(idea));
        }

        [HttpGet, Route("{id}/pages")]
        // GET: Idea/Pages
        public async Task<IActionResult> Pages(string id)
        {
            var idea = await _ideaService.GetIdeaAsync(id);

            return View(IdeaInfoViewModel.MapFrom(idea));
        }

        [HttpGet, Route("index")]
        public IActionResult Index()
        {
            return View("Search", IdeaSearchViewModel.CreateWithKeyword(string.Empty));
        }

        [HttpGet, Route("search/{query}")]
        public IActionResult Search(string query)
        {
            return View("Search", IdeaSearchViewModel.CreateWithKeyword(query));
        }

        [HttpPost, Route("{id}/publish")]
        public IActionResult Publish(string id)
        {
            _ideaService.PublishAsync(id);
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpPost, Route("{id}/unpublish")]
        public IActionResult Unpublish(string id)
        {
            _ideaService.UnpublishAsync(id);
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet, Route("{id}/teamdetails")]
        public IActionResult Teamdetails(string id)
        {
            return RedirectToAction(nameof(TeamController.Details), "Team", new { id });
        }

    }
}

src/ProIdeas.UI/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ProIdeas.Services.Contracts;
using System.Threading.Tasks;
using ProIdeas.UI.Models.User;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ProIdeas.UI.Controllers
{
    [Authorize]    
    public class UserController : Controller
    {
        private readonly IIdeaCollaborationService _collaborationService;

     
        public UserController(IIdeaCollaborationService collaborationService)
        {
            _collaborationService = collaborationService;
        }
        // GET: /<controller>/
        [Route("profile/{id}")]
        public async Task<IActionResult> Details(string id)
        {
          var model = UserActivityViewModel.MapFrom(
              await _collaborationService.GetActivitiesAsync(id),
              await _collaborationService.GetContributionsAsync(id), id);
          return View(model);
        }
    }
}

src/ProIdeas.UI/ViewComponents/TeamMemberStatusViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ProIdeas.Services;
using ProIdeas.UI.Models.TeamViewModels;
using System.Threading.Tasks;

namespace ProIdeas.UI.ViewComponents
{
    public class TeamMemberStatusViewComponent : ViewComponent
    {
        private readonly ITeamService _teamService;
        public TeamMemberStatusViewComponent(ITeamService teamService)
        {
            _teamService = teamService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string userId,string ideaId)
        {
            var model = TeamMemberViewModel.MapFrom(await _teamService.GetTeamMemberAsync(userId, ideaId), ideaId, userId);
            return View(model);
        }
    }
}

src/ProIdeas.UI/Views/Idea/Create.cshtml
@model IdeaInfoViewModel
@{
    ViewData["Title"] = "Post New Idea";
}

@section Styles{
    <link href="~/css/quill.core.css" rel="stylesheet" />
    <link href="~/css/quill.snow.css" rel="stylesheet" />
}

@section Scripts{
    <script src="~/Scripts/pages/ideas/create.bundle.js" asp-append-version="true"></script>
}

<div class="container create-idea create-idea l-padding white-background">    
    @await Html.PartialAsync("_AddEditForm", Model);
</div>

src/ProIdeas.UI/Views/Idea/Details.cshtml
@model IdeaInfoViewModel
@{

    Layout = "_LayoutFulid";
    ViewData["Title"] = Model.Title;
}

@section Scripts{
    <script src="~/Scripts/pages/ideas/details.bundle.js" asp-append-version="true"></script>
}

@inject UserManager<ApplicationUser> UserManager

<div class="idea-details-page-wrap">
    <div class="col-lg-8">
        <div class="idea-details-page white-background">
            <div class="row">
                <div class="idea-header">
                    <div class="col-sm-6">
                        <img src="/api/ideas/@Model.Id/banner.png" alt="Circle Image" class="img-responsive">
                    </div>
                    <div class="col-sm-6">
                        <div class="name xl-top-margin">
                            <h2>@Model.Title</h2>
                            <span class="author-wrap">By <a asp-controller="User" asp-action="Details" asp-route-id="@Model.OwnerId" class="author">@Model.Owner.FullName</a></span>
                        </div>
                        <div class="pull-left width250px">
                            <div>
                                <idea-like params="like: '@Model.Likes', ideaId: '@Model.Id', client: client"></idea-like>
                            </div>
                            @if (Model.IsOwner(UserManager.GetUserId(User)))
                        {
                                <div>
                                    <div class="display-inline">
                                        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-default">Edit</a>
                                    </div>

                                    @if (Model.IsPublished)
                            {
                                        <div class="display-inline">
                                            <form class="form-inline" method="post" asp-action="Unpublish" asp-route-id="@Model.Id">
                                                <button class="btn btn-primary">Unpublish</button>
                                            </form>
                                        </div>
                            }
                            else
                            {
                                        <div class="display-inline">
                                            <form class="form-inline" method="post" asp-action="Publish" asp-route-id="@Model.Id">
                                                <button class="btn btn-primary">Publish</button>
                                            </form>
                                        </div>
                            }
                                </div>
                        }
                        else
                        {
                                <div class="display-inline">
                                    @await Component.InvokeAsync("TeamMemberStatus", new { userId = UserManager.GetUserId(User), ideaId = Model.Id })
                                </div>
                        }
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="profile-tabs">
                    <div class="nav-align-left">
                        <ul class="nav nav-pills nav-pills-grey" role="tablist">
                            @foreach (var page in Model.Pages)
                            {
                                <li class="@(page.IsActive ? "active" : string.Empty)">
                                    <a href="#@page.Id" role="tab" data-toggle="tab">
                                        @page.Name
                                    </a>
                                </li>
                            }

                            @if (Model.IsFundingRequired)
                            {
                                <li>
                                    <a href="#fundingdetails" role="tab" data-toggle="tab">
                                        Funding Requirement
                                    </a>
                                </li>

                            }
                        </ul>

                        <div class="tab-content gallery">
                            @foreach (var page in Model.Pages)
                            {
                                <div class="tab-pane l-margin @(page.IsActive ? "active" : string.Empty)" id="@page.Id">
                                    <div class="col-sm-10">
                                        @Html.Raw(page.Content)
                                    </div>
                                </div>
                            }
                            @if (Model.IsFundingRequired)
                            {
                                <div class="tab-pane l-margin" id="fundingdetails">
                                    <div class="col-sm-10">
                                        @Html.Raw(Model.FundingRequirement)
                                    </div>
                                </div>

                            }
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <comments-list params="ideaId: '@Model.Id', client: client, userId: '@UserManager.GetUserId(User)'"></comments-list>
    </div>
</div>

src/ProIdeas.UI/Views/Idea/Edit.cshtml
@model IdeaInfoViewModel
@{
    ViewData["Title"] = "Edit Idea";
}

@section Styles{
    <link href="~/css/quill.core.css" rel="stylesheet" />
    <link href="~/css/quill.snow.css" rel="stylesheet" />
}

@section Scripts{
    <script src="~/Scripts/pages/ideas/edit.bundle.js" asp-append-version="true"></script>    
}

<div class="container create-idea l-padding white-background">
    @await Html.PartialAsync("_AddEditForm", Model);
</div>

src/ProIdeas.UI/Views/Idea/Images.cshtml
@model IdeaInfoViewModel
@{
    ViewData["Title"] = "Edit Idea Images";
}

@section Scripts{
    <script src="~/Scripts/pages/ideas/images.bundle.js" asp-append-version="true"></script>
}
<input id="IdeaId" type="hidden" value="@Model.Id" />
<div class="container create-idea l-padding white-background">
    <div>
        <h4 class="common-page-header">Post your new idea</h4>
        <section>
            <ul class="nav nav-pills nav-pills-vertical" role="tablist">
                <li class="complete"><a href="/ideas/@Model.Id/edit">Basic Information</a></li>
                <li class="active"><a href="/ideas/@Model.Id/images">Images</a></li>
                <li class=""><a href="/ideas/@Model.Id/teamdetails">Team</a></li>
                <li class=""><a href="/ideas/@Model.Id/pages">Pages</a></li>
                @*<li class=""><a href="#payments">Review</a></li>*@
            </ul>
            <div class="content" id="idea-image-upload-form">
                <div data-bind="with: form">
                    <file-uploader params="icon: file.icon, value: file.value"></file-uploader>
                    <p><b>*Note: Suggested image dimension 555 X 400 in pixels</b></p>
                    <div data-bind="if: file.selectedFile" class="card card-profile card-plain">
                        <img alt="Banner Image" height="400" width="555" data-bind="attr:{src: file.selectedFile}" title="Selected Banner Image"/>
                        
                    </div>

                </div>
                <div>
                    <button class="btn btn-primary pull-right" data-bind="click: save">Next</button>
                    <a asp-controller="Idea" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-secondary pull-right">Previous</a>
                </div>
            </div>
        </section>
    </div>
</div>

src/ProIdeas.UI/Views/Idea/Pages.cshtml
@model IdeaInfoViewModel
@{
    ViewData["Title"] = "Edit Idea Pages";
}

@section Styles{
    <link href="~/css/quill.core.css" rel="stylesheet" />
    <link href="~/css/quill.snow.css" rel="stylesheet" />
}

@section Scripts{
    <script src="~/Scripts/pages/ideas/pages.bundle.js" asp-append-version="true"></script>
}

<script id="pages-template" type="text/html">
    <div>
        <aside class="col-sm-3">
            <ul class="nav nav-pills nav-stacked nav-pills-horizontal nav-pills-success nav-pills-with-btn" data-bind="foreach: pages">
                <li class="active" data-bind="css:{ active: $parent.isCurrentPage($data) },click: function(){$parent.editPage($data);}">
                    <a>
                        <span data-bind="text: name"></span>
                    </a>
                    <button class="btn btn-danger btn-xs btn-simple" data-bind="if: canDelete,click: function(){ $parent.removePage($data);}">
                        <i class="material-icons pull-right">delete</i>
                    </button>
                </li>
            </ul>
            <button class="btn btn-simple create-page" data-bind="if: canAddPage, click: addPage">
                <i class="material-icons">add</i><span>Create New Page</span>
            </button>
        </aside>
        <content class="col-sm-9 tab-content" data-bind="if: currentPage">
            <div class="col-sm-12 input-group" data-bind="with: currentPage()">
                <div class="col-sm-12 input-group">
                    <div class="form-group is-empty">
                        <input class="form-control" type="text" placeholder="Enter page name" autocomplete="off" data-bind="enable: canDelete, textInput: name" />
                        <span class="material-icons form-control-feedback">clear</span>
                        <span class="material-input"></span>
                        <span class="help-block validation-message"></span>
                    </div>
                </div>
                <div class="col-sm-12 input-group">
                    <rich-text-editor params="placeholder:'Page content',mode:'all',value: content"></rich-text-editor>
                </div>
            </div>
        </content>
    </div>
    <div>
        <button class="btn btn-primary pull-right" data-bind="click: finish">Review</button>
        <a asp-controller="Idea" asp-action="Images" asp-route-id="@Model.Id" class="btn btn-secondary pull-right">Previous</a>
    </div>
</script>

<input id="IdeaId" type="hidden" value="@Model.Id" />

<div class="container create-idea l-padding white-background">
    <h4 class="common-page-header">Post your new idea</h4>

    <div>
        <section>
            <ul class="nav nav-pills nav-pills-vertical" role="tablist">
                <li class="complete"><a href="/ideas/@Model.Id/edit">Basic Information</a></li>
                <li class="complete"><a href="/ideas/@Model.Id/images">Images</a></li>
                <li class="complete"><a href="/ideas/@Model.Id/teamdetails">Team</a></li>
                <li class="active"><a href="/ideas/@Model.Id/pages">Pages</a></li>
                @*<li class=""><a href="#payments">Review</a></li>*@
            </ul>
        </section>
        <section class="content" id="idea-pages" data-bind="template:{name:'pages-template'}"></section>
    </div>
</div>

src/ProIdeas.UI/Views/Idea/Search.cshtml
@model IdeaInfoViewModel
@{
    ViewData["Title"] = "Search Ideas";
}

@section Styles{
    <link href="~/css/quill.core.css" rel="stylesheet" />
    <link href="~/css/quill.snow.css" rel="stylesheet" />
}

@section Scripts{
    <script src="~/Scripts/pages/ideas/pages.bundle.js"></script>
}

<div class="container create-idea l-padding white-background" id="search-container">

    <section class="row">
        <div class="col-sm-12 input-group">
            <input type="text" class="form-control" placeholder="Search for ideas" data-bind="textInput: keyword" />
            <div class="input-group-btn">
                <button type="button" class="btn btn-default" data-bind="click: search">
                    <span class="material-icons">search</span>
                </button>
            </div>
        </div>
    </section>
    <section class="row">
        <div class="content" data-bind="foreach: results">
            <div class="col-sm-4 idea-card-wrap">
                <div class="idea-card">
                    <div class="card-image"><img data-bind="attr:{src:banner}" /></div>
                    <div class="card-content-container">
                        <h3 class="card-header" data-bind="text: title"></h3>
                        <span class="author-wrap">Share by <span class="author">Gopi Krishna J</span></span>
                        <p class="card-content" data-bind="description: title">
                        </p>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-simple idea-like"><i class="material-icons">favorite</i><span data-bind="text: likes">12</span></button>
                        <button class="btn btn-simple idea-comment"><i class="material-icons">insert_comment</i><span data-bind="text: comments">25</span></button>
                    </div>
                </div>
            </div>
        </div>

    </section>

</div>

src/ProIdeas.UI/Views/Idea/_AddEditForm.cshtml
@model IdeaInfoViewModel

<div>
    <h4 class="common-page-header">
        @(string.IsNullOrEmpty(Model.Id) ? "Post New Idea" : "Edit Idea")
    </h4>
    <section>
        <ul class="nav nav-pills nav-pills-vertical" role="tablist">
            <li class="active"><a href="javascript:void()">Basic Information</a></li>
            @if (string.IsNullOrEmpty(Model.Id))
            {
                <li class="disabled"><a href="javascript:void()">Images</a></li>
                <li class="disabled"><a href="javascript:void()">Team</a></li>
                <li class="disabled"><a href="javascript:void()">Pages</a></li>
            }
            else
            {
                <li class=""><a href="/ideas/@Model.Id/images">Images</a></li>
                <li class=""><a href="/ideas/@Model.Id/teamdetails">Team</a></li>
                <li class=""><a href="/ideas/@Model.Id/pages">Pages</a></li>
            }

            @*<li class=""><a href="#payments">Review</a></li>*@
        </ul>
        <div class="content">
            <form id="create-idea-form" class="form" data-bind="submit: save">
                <div class="col-sm-12 input-group">
                    <div class="form-group" data-bind="validationElement: form().title">
                        <input class="form-control" value="" type="text" placeholder="Name your idea *" autocomplete="off" data-bind="textInput: form().title" />
                        <span class="material-icons form-control-feedback">clear</span>
                        <span class="material-input"></span>
                    </div>
                </div>
                <div class="col-sm-12 input-group">
                    <div class="form-group" data-bind="validationElement: form().description">
                        <textarea class="form-control" value="" placeholder="Description your idea *" autocomplete="off" data-bind="value: form().description"></textarea>
                        <span class="material-icons form-control-feedback">clear</span>
                        <span class="material-input"></span>
                    </div>
                </div>
                <div class="col-sm-12 input-group" data-bind="validationElement: form().fundingRequirement">
                    <rich-text-editor params="placeholder:'Describe if your idea require funding.',mode:'all',value: form().fundingRequirement"></rich-text-editor>
                </div>
                <button class="btn btn-primary pull-right" type="submit">Next</button>
            </form>
        </div>
    </section>
    <input id="IdeaId" type="hidden" value="@Model.Id" />
</div>