src/ProIdeas.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProIdeas.Authentication.Contracts;
using ProIdeas.DTO;
using ProIdeas.Services.Contracts;
using ProIdeas.UI.Models.IdeaViewModels;
using System.Linq;
using System.Threading.Tasks;


namespace ProIdeas.UI.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IIdeaService _ideaService;
        private readonly IUserIdentityProvider _userIdentityProvider;

        public HomeController(IIdeaService ideaService, IUserIdentityProvider userIdentityProvider)
        {
            _ideaService = ideaService;
            _userIdentityProvider = userIdentityProvider;
        }


        public IActionResult Index()
        {
            return View(IndexIdeasViewModel.MapFrom(Enumerable.Empty<IdeaDto>()));
        }

        public async Task<IActionResult> MyIdeas()
        {
            var ideas = await _ideaService.GetUserIdeasAsync(_userIdentityProvider.GetUserId(), 10, 1, string.Empty);

            return View(IndexIdeasViewModel.MapFrom(ideas));
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/ProIdeas.UI/ViewComponents/IdeaBannerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ProIdeas.Services.Contracts;
using ProIdeas.UI.Models.IdeaViewModels;
using System.Threading.Tasks;

namespace ProIdeas.UI.ViewComponents
{
    public class IdeaBannerViewComponent: ViewComponent
    {
        private readonly IIdeaService _ideaService;
        public IdeaBannerViewComponent(IIdeaService ideaService)
        {
            _ideaService = ideaService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = IdeaBannerViewModel.MapFrom(await _ideaService.GetTopIdeasAsync(3));
            return View(model);
        }
    }
}

src/ProIdeas.UI/Views/Home/Index.cshtml
@model IndexIdeasViewModel
@{
    ViewData["Title"] = "Home";
}
@section Scripts{
    <script src="~/Scripts/pages/ideas/search.bundle.js"></script>
}


<script type="text/html" id="search-page-template">
    <div class="row l-top-margin l-bottom-margin">
        <div class="col-sm-8">
            <h3 class="search-title">Explore Ideas</h3>
        </div>
        <div class="col-sm-4">
            <form class="form search-box-wrap l-top-margin" data-bind="submit: search">
                <input class="search-box" placeholder="Search for ideas..." data-bind="textInput: keyword" />
                <i class="search-icon material-icons">search</i>
            </form>
        </div>
    </div>
    <div class="row"  data-bind="foreach: collection">
        <div class="col-sm-4 idea-card-wrap">
            <idea-card params="idea: $data, like: $parent.like, comment: $parent.comment"></idea-card>
        </div>
    </div>
</script>
<div class="row s-top-margin">
    @await Component.InvokeAsync("IdeaBanner")
</div>

    <div id="ideas-search-container">
        <div class="row">
            <div class="search-form-container" data-bind="template: {name:'search-page-template'}">
            </div>
        </div>
    </div>

@await Html.PartialAsync("_FloatingButtons")

src/ProIdeas.UI/Views/Home/MyIdeas.cshtml
@model IndexIdeasViewModel
@{
    ViewData["Title"] = "My Ideas";
}
@section Scripts{
    <script src="~/Scripts/pages/ideas/searchMyIdeas.bundle.js"></script>
}

<script type="text/html" id="search-page-template">
    <div class="row l-top-margin l-bottom-margin">
        <div class="col-sm-8">
            <h3 class="search-title">Ideas flashed in my head!</h3>
        </div>
        <div class="col-sm-4">
            <form class="form search-box-wrap l-top-margin" data-bind="submit: search">
                <input class="search-box" placeholder="Search for ideas..." data-bind="textInput: keyword" />
                <i class="search-icon material-icons">search</i>
            </form>
        </div>
    </div>
    <div class="row" data-bind="foreach: collection">
        <div class="col-sm-4 idea-card-wrap">
            <idea-card params="idea: $data, like: $parent.like, comment: $parent.comment"></idea-card>
        </div>
    </div>
</script>

<div id="ideas-search-container">
    <div class="row">
        <div class="search-form-container" data-bind="template: {name:'search-page-template'}">
        </div>
    </div>
</div>

@await Html.PartialAsync("_FloatingButtons")