src/ProIdeas.UI/Controllers/IdeaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProIdeas.Services.Contracts;
using ProIdeas.UI.Models.IdeaViewModels;
using System.Threading.Tasks;
using System.Linq;

namespace ProIdeas.UI.Controllers
{
    [Authorize]
    [Route("ideas")]
    public class IdeaController : Controller
    {
        private readonly IIdeaService _ideaService;
        public IdeaController(IIdeaService ideaService)
        {
            _ideaService = ideaService;
        }

        // GET: Idea/Details/5
        [HttpGet, Route("{id}/details")]
        public async Task<IActionResult> Details(string id)
        {
            var idea = await _ideaService.GetIdeaAsync(id);

            var model = IdeaInfoViewModel.MapFrom(idea);
            if (model.Pages.Any())
            {
                model.Pages.First().IsActive = true;
            }

            return View(model);
        }

        [HttpGet, Route("create")]
        // GET: Idea/Create
        public IActionResult Create()
        {
            return View(IdeaInfoViewModel.CreateEmpty());
        }

        [HttpGet, Route("{id}/edit")]
        // GET: Idea/Edit
        public async Task<IActionResult> Edit(string id)
        {
            var idea = await _ideaService.GetIdeaAsync(id);

            return View(IdeaInfoViewModel.MapFrom(idea));
        }


        [HttpGet, Route("{id}/images")]
        // GET: Idea/Images
        public async Task<IActionResult> Images(string id)
        {
            var idea = await _ideaService.GetIdeaAsync(id);

            return View(IdeaInfoViewModel.MapFrom(idea));
        }

        [HttpGet, Route("{id}/pages")]
        // GET: Idea/Pages
        public async Task<IActionResult> Pages(string id)
        {
            var idea = await _ideaService.GetIdeaAsync(id);

            return View(IdeaInfoViewModel.MapFrom(idea));
        }

        [HttpGet, Route("index")]
        public IActionResult Index()
        {
            return View("Search", IdeaSearchViewModel.CreateWithKeyword(string.Empty));
        }

        [HttpGet, Route("search/{query}")]
        public IActionResult Search(string query)
        {
            return View("Search", IdeaSearchViewModel.CreateWithKeyword(query));
        }

        [HttpPost, Route("{id}/publish")]
        public IActionResult Publish(string id)
        {
            _ideaService.PublishAsync(id);
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpPost, Route("{id}/unpublish")]
        public IActionResult Unpublish(string id)
        {
            _ideaService.UnpublishAsync(id);
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet, Route("{id}/teamdetails")]
        public IActionResult Teamdetails(string id)
        {
            return RedirectToAction(nameof(TeamController.Details), "Team", new { id });
        }

    }
}

src/ProIdeas.UI/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ProIdeas.Services.Contracts;
using System.Threading.Tasks;
using ProIdeas.UI.Models.User;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ProIdeas.UI.Controllers
{
    [Authorize]    
    public class UserController : Controller
    {
        private readonly IIdeaCollaborationService _collaborationService;

     
        public UserController(IIdeaCollaborationService collaborationService)
        {
            _collaborationService = collaborationService;
        }
        // GET: /<controller>/
        [Route("profile/{id}")]
        public async Task<IActionResult> Details(string id)
        {
          var model = UserActivityViewModel.MapFrom(
              await _collaborationService.GetActivitiesAsync(id),
              await _collaborationService.GetContributionsAsync(id), id);
          return View(model);
        }
    }
}

src/ProIdeas.UI/ViewComponents/ProfileViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ProIdeas.Services.Contracts;
using ProIdeas.UI.Models.User;
using System.Threading.Tasks;

namespace ProIdeas.UI.ViewComponents
{
    public class ProfileViewComponent : ViewComponent
    {
        private readonly IUserProfileService _userProfileService;
        public ProfileViewComponent(IUserProfileService userProfileService)
        {
            _userProfileService = userProfileService;
        }
        public async Task<IViewComponentResult> InvokeAsync(string userId)
        {
            var model = UserProfileViewModel.MapFrom(await _userProfileService.GetUserProfileAsync(userId));
            return View(model);
        }
    }
}

src/ProIdeas.UI/Views/User/Details.cshtml
@model  UserActivityViewModel

@section Scripts{
    <script src="~/Scripts/pages/generic.bundle.js"></script>
}

<div class="row s-left-padding white-background">
    <div class="col-md-3">
        @await Component.InvokeAsync("Profile", new { userId = Model.OwnerId })
    </div>
    <div class="col-md-9">
        @await Html.PartialAsync("_NavigationBar", Model)

        <section class="tab-content">
            @*User Actions*@
            <div class="s-margin tab-pane active" id="contributions">
                @if (!Model.UserContributions.Any())
                {
                    <div class="alert alert-nocontent nocontent-padding" role="alert">It seems you don't have any contributions. Good time to start!!</div>
                }
                <ul class="timeline timeline-inverse">
                    @foreach (var activity in Model.UserContributions)
                    {
                        <li class="time-label">
                            <span class="bg-red">@activity.ActivityDate</span>
                        </li>

                        foreach (var item in activity.ActivityTimeLine)
                        {
                            @await Html.PartialAsync(item.Activity.ActivityType, item)
                        }
                    }
                </ul>
            </div>

            @*User Timeline*@
            <div class="s-margin tab-pane" id="timeline">
                @if (!Model.UserActivities.Any())
                {
                    <div class="alert alert-nocontent nocontent-padding " role="alert">It seems you don't have any activities. Good time to start!!</div>
                }
                <ul class="timeline timeline-inverse">
                    @foreach (var activity in Model.UserActivities)
                    {
                        <li class="time-label">
                            <span class="bg-red">@activity.ActivityDate</span>
                        </li>
                        foreach (var item in activity.ActivityTimeLine)
                        {
                            @await Html.PartialAsync(item.Activity.ActivityType, item)
                        }
                    }
                </ul>
            </div>
        </section>
    </div>
</div>

src/ProIdeas.UI/Views/User/_NavigationBar.cshtml
@model  UserActivityViewModel

<section>
    <ul class="nav nav-pills nav-pills-vertical">
        <li class="s-margin m-right-margin active">
            <a data-toggle="tab" href="#contributions">Contributions</a>
        </li>
        <li class="s-margin m-right-margin" data-toggle="tab" href="#timeline"><a>Timeline</a></li>
    </ul>
</section>

src/ProIdeas.UI/Views/User/ideas.comments.create.cshtml
@model  ActivitiesTimeLineViewModel

<li>
    <i class="fa fa-comments bg-yellow"></i>
    <div class="timeline-item">
        <span class="time">
            <i class="fa fa-clock-o"></i>&nbsp;@Model.ActivityDuration
        </span>
        <h3 class="timeline-header">
            @if (Model.ActivityOwner.self) {
            <b>You</b>
            }
            else
            {
                <a asp-controller="User" asp-route-id="@Model.ActivityOwner.Id">@Model.ActivityOwner.FullName</a>
            }
            commented on
            <a  asp-controller="Idea" asp-route-id="@Model.Activity.IdeaId">idea</a>
        </h3>
        <div class="timeline-body">
            @Model.Activity.Details
        </div>
        <div class="timeline-footer">
            <a asp-controller="Idea" asp-route-id="@Model.Activity.IdeaId"  class="btn btn-warning btn-flat btn-xs">View idea</a>
        </div>
    </div>

</li>

src/ProIdeas.UI/Views/User/ideas.create.cshtml
@model  ActivitiesTimeLineViewModel

<li>
    <i class="fa fa-flash bg-blue"></i>
    <div class="timeline-item">
        <span class="time">
            <i class="fa fa-clock-o"></i>&nbsp;@Model.ActivityDuration
        </span>
        <h3 class="timeline-header">
          @if (Model.ActivityOwner.self)
          {
            <b>You</b>
          }
          else
          {
            <a asp-controller="User" asp-route-id="@Model.ActivityOwner.Id">@Model.ActivityOwner.FullName</a>
          } shared an
            <a asp-controller="Idea" asp-route-id="@Model.Activity.IdeaId">idea</a>
        </h3>
        <div class="timeline-body">
            @Model.Activity.Details
        </div>
        <div class="timeline-footer">
            <a asp-controller="Idea" asp-route-id="@Model.Activity.IdeaId" class="btn btn-primary btn-xs">View idea</a>
        </div>
    </div>

</li>

src/ProIdeas.UI/Views/User/ideas.publish.cshtml
@model  ActivitiesTimeLineViewModel

<li>
    <i class="fa fa-flash bg-blue"></i>
    <div class="timeline-item">
        <span class="time">
            <i class="fa fa-clock-o"></i>&nbsp;@Model.ActivityDuration
        </span>
        <h3 class="timeline-header">
          @if (Model.ActivityOwner.self)
          {
            <b>You</b>
          }
          else
          {
            <a asp-controller="User" asp-route-id="@Model.ActivityOwner.Id">@Model.ActivityOwner.FullName</a>
          } published an
            <a asp-controller="Idea" asp-route-id="@Model.Activity.IdeaId">idea</a>
        </h3>
        <div class="timeline-body">
            @Model.Activity.Details
        </div>
        <div class="timeline-footer">
            <a asp-controller="Idea" asp-route-id="@Model.Activity.IdeaId" class="btn btn-primary btn-xs">View idea</a>
        </div>
    </div>

</li>

src/ProIdeas.UI/Views/User/ideas.votes.cshtml
@model  ActivitiesTimeLineViewModel

<li>
    <i class="fa fa-thumbs-up bg-blue"></i>
    <div class="timeline-item">
        <span class="time">
            <i class="fa fa-clock-o"></i>&nbsp;@Model.ActivityDuration
        </span>
        <h3 class="timeline-header">
           @if (Model.ActivityOwner.self)
           {
            <b>You</b>
           }
           else
           {
            <a asp-controller="User" asp-route-id="@Model.ActivityOwner.Id">@Model.ActivityOwner.FullName</a>
           }
            liked an
            <a asp-controller="Idea" asp-route-id="@Model.Activity.IdeaId">idea</a>
        </h3>
    </div>

</li>